// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnikOpstart.Services.MedarbejderKompetencer.Database.SqlContext;

#nullable disable

namespace UnikOpstart.Services.Database.SqlMigrations.Migrations
{
    [DbContext(typeof(MedarbejderKompetencerContext))]
    [Migration("20221209171626_RebuildDatabase")]
    partial class RebuildDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("UnikOpstart.Services.MedarbejderKompetencer.Domain.Models.KompetenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Egenskab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedarbejderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KompetenceEntities");
                });

            modelBuilder.Entity("UnikOpstart.Services.MedarbejderKompetencer.Domain.Models.MedarbejderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedarbejderEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
