// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnikOpstart.Services.Booking.Database.SqlContext;

#nullable disable

namespace UnikOpstart.Services.Database.SqlMigrations.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20221213103814_DatatimeConversion")]
    partial class DatatimeConversion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("UnikOpstart.Services.Booking.Domain.Models.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedarbejderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpgaveId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SlutDato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
